title: growing home for you
author:
  name: GitHub User1001
  email: xiongsi@kean.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Home is a very functional building. The evolution of housing is always improving towards practicality and Home is changing accordingly to human needs. Each family has different needs for their own home, and it is very difficult to make a model home fit all customers. So I think the most basic thing about home is to meet the basic needs of people. For example, the function of bedroom, kitchen and toilet is essential. With this requirement, home can be transformed into a patterned and copy-and-paste thing. This is cost saving and convenient. The future of homes that people are now looking for is a model building that can meet the needs of more people. This kind of housing can solve more problems, such as the use of anti-mosquito materials.
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
theme: minima
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
